### ISSUE TITLE
match case validation too strict

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#103]
This is a bug from the future; see https://github.com/ceylon/ceylon/issues/5754

`MatchCase` should allow `QualifiedExpression`s in which the `receiverExpression` is a `Package`.

For example, this code should be allowed:

```ceylon
interface Event of nil | eof {}
object nil satisfies Event {}
object eof satisfies Event {}

void onEvent(Anything() nil, Anything() eof, Event event) {
    switch(event)
    case (package.nil) { nil(); }
    case (package.eof) { eof(); }
}

shared void run() {
    onEvent(curry(print)("nil"), curry(print)("eof"), eof);
}
```

but currently results in
```
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated is IntegerLiteral|CharacterLiteral|StringLiteral|NegationOperation|BaseExpression expression = expressionToCeylon(element, update)"
	at ceylon.ast.redhat.matchCaseToCeylon_$2.$call$(MatchCase.ceylon:26)
```
for the `Tree`
```
|  |  |  |  |  |  +  [MatchCase] (7:10-7:21)
|  |  |  |  |  |  |  +  [ExpressionList] (7:10-7:20)
|  |  |  |  |  |  |  |  +  [Expression] (7:10-7:20) : nil
|  |  |  |  |  |  |  |  |  +  [QualifiedMemberExpression] (7:10-7:20) : nil : nil : value nil => nil
|  |  |  |  |  |  |  |  |  |  + nil [Identifier] (7:18-7:20)
|  |  |  |  |  |  |  |  |  |  +  [InferredTypeArguments]
|  |  |  |  |  |  |  |  |  |  + package [Package] (7:10-7:16) : unknown
|  |  |  |  |  |  |  |  |  |  + . [MemberOp] (7:17-7:17)
```

**Comment by lucaswerkmeister** [comment]
The spec commit fixing this is ceylon/ceylon@58d23683928e79445db417c14bacca56f7e484ad. That commit adds essentially no information for us, though, since it just adds `ConstructorExpression`, which we don’t have (indistinguishable from any `MemberExpression` without typechecking). In addition, the spec already covered `package.nil` with `BaseExpression`, which includes an optional `package` qualifier in the spec, but not in `ceylon.ast`.

So what we need to do is to allow `QualifiedExpression` where the `receiverExpression` is a `BaseExpression|MemberExpression|Package`. We *could* also check if the `MemberExpression` is the right kind of member expression, i. e. one that can reference a class. Should we do that? Should we even check the `QualifiedExpression`’s `receiverExpression`?

**Comment by gavinking** [comment]
The only things that are legal here are of form:

- `true`
- `package.true`
- `Boolean.true`
- `package.Boolean.true`

That's it. Even if the spec grammar accepts slightly more than that, the text is very clear that these are the only meaningful possibilities.

**Comment by lucaswerkmeister** [comment]
Yes, but I doubt whether `ceylon.ast` should really test if you’re doing `package.Boolean.true` and not `somethingElse.Boolean.true`. I think that goes too far.

**Comment by gavinking** [comment]
Well I didn't even bother encoding that into the spec grammar, so you can form your own conclusions from that ;-)

**Comment by lucaswerkmeister** [comment]
Oh damn, I just remembered that I wanted to do all `ceylon.ast` work for now on branches… @jvasileff do you mind if I rewrite history to make that commit on `1.2.0` and then merge it into `master`?

**Comment by jvasileff** [comment]
no, please do!

**Comment by lucaswerkmeister** [comment]
Alright, done. See branch `matchCaseQualifiedExpression`.
