### ISSUE TITLE
optimize Node.visitChildren()

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#107]
`Node.visitChildren()` delegates to `transformChildren()`, which unnecessarily instantiates a sequence:

```ceylon
    shared Result[] transformChildren<out Result>(Transformer<Result> transformer) => [
        for (child in children)
            child.transform(transformer)
    ];
...
    shared void visitChildren(Visitor visitor) => transformChildren(visitor);
```

so perhaps `visitChildren` should be rewritten as:

```ceylon
    shared void visitChildren(Visitor visitor) {
        for (child in children) {
            child.transform(visitor);
        }
    }
```

based on tests against sdk modules, this has the potential to drop processing times by 40%+ for `Visitor`s that don't perform expensive tasks.

**Comment by jvasileff** [comment]
I can try this out later.

**Comment by lucaswerkmeister** [comment]
Done. I call `child.visit` instead of `child.transform`, because:
- `Visitor.transform` just delegates to `visit` without clients being able to change that; you’d hope the JVM would realize this and inline the call, but still, for “`Visitor`s that don’t perform expensive tasks”, the whole job might be done before optimization kicks in here.
- It makes more sense for `visitChildren` to call `visit`.
- It actually matches the documentation now, which says “calls `visit`”. It wasn’t *wrong* before, per above, but still.

**Comment by jvasileff** [comment]
Thanks @lucaswerkmeister, this provides a very nice performance boost. After warmup for a node-counting visitor, I'm seeing seeing an improvement from 1.2.0's `79.72ms` to a new time of `41.49ms`.

Now, this compares to `14.76ms` and `14.91ms` times using a typechecker visitor as a control. More on that to come...
