### ISSUE TITLE
support specification statements in Interfaces

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#91]
This typechecks:

```ceylon
interface I1 {
    shared formal String something();
}

interface I2 satisfies I1 {
    something() => "";
}
```

but is not supported by `InterfaceBody`, and consequently blows up `interfaceBodyToCeylon`:

```
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated is JDeclaration statement"
	at ceylon.ast.redhat.interfaceBodyToCeylon_$2.$call$(InterfaceBody.ceylon:22)
	at ceylon.ast.redhat.interfaceBodyToCeylon_$2.$call$(InterfaceBody.ceylon:21)
	at ceylon.language.Iterable$impl$3$1$1.next(Iterable.ceylon:345)
```

**Comment by lucaswerkmeister** [comment]
Per spec, `something() => "";` is a `LazySpecification`, which is a `Statement`, not a `Declaration`, and therefore not allowed in an `InterfaceBody`. As far as I can tell, it is a typechecker bug that `I2` is not rejected. @gavinking?

(You can also see this in regular classes: [this comment in `LinkedList.ceylon`](https://github.com/ceylon/ceylon-sdk/blob/8ccfb955149a5dc7aa3a2233c3029b9195a64176/source/ceylon/collection/LinkedList.ceylon#L41) is incorrect, since [some shortcut refinements](https://github.com/ceylon/ceylon-sdk/blob/8ccfb955149a5dc7aa3a2233c3029b9195a64176/source/ceylon/collection/LinkedList.ceylon#L917-L935) extend the initializer section all the way to the bottom of the file, as can be seen in the IDE.)

**Comment by gavinking** [comment]
No, it's a shortcut refinement, and *totally* allowed.

**Comment by gavinking** [comment]
Ah, but indeed the grammar in the spec does not make clear that shortcut refinements are allowed in interface bodies. I need to fix that.

**Comment by gavinking** [comment]
Fixed in https://github.com/ceylon/ceylon-spec/issues/1389.

**Comment by jvasileff** [comment]
As you can [see](https://github.com/ceylon/ceylon-spec/commit/fac586b77364a40176a95f60d535f792d3cfe0b0), @lucaswerkmeister, this was a report for a future bug, which has now materialized. Or, more charitably, it is an enhancement request to bring Ceylon AST in compliance with the current Ceylon Language Specification.
