### ISSUE TITLE
crash on valid Float values

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#98]
Ceylon 1.2's `parseFloat()` is unreliable, and returns `null` for:

```
parseFloat("3.14159265358979323846")
```
and throws for `2.7182818284590452354`, causing `ceylon.ast` exceptions like:
```
ceylon compile-dart: 8736074210880900738 cannot be coerced into a 64 bit floating point value
ceylon.language.OverflowException "8736074210880900738 cannot be coerced into a 64 bit floating point value"
	at ceylon.language.Integer.getFloat(Integer.java:442)
	at ceylon.language.parseFloat_.parseFloat(parseFloat.ceylon:86)
	at ceylon.ast.core.FloatLiteral.<init>(FloatLiteral.ceylon:22)
	at ceylon.ast.redhat.floatLiteralToCeylon_.floatLiteralToCeylon(FloatLiteral.ceylon:21)
	at ceylon.ast.redhat.literalToCeylon_.literalToCeylon(Literal.ceylon:36)
```
yet these are both valid Float values.

Of course, *any* routine to convert `String` to `Float` may suffer loss of precision, so even without the crash, use of `FloatLiteral.float` is probably ill-advised.

It could be made lazy (or even return `Float?`) to give `ceylon.ast` users a chance to avoid the crash, but it may make sense to remove the attribute entirely.

**Comment by tombentley** [comment]
On 20 Oct 2015 05:29, "John Vasileff" <notifications@github.com> wrote:
>
> Ceylon 1.2's parseFloat() is unreliable, and returns null for:
>
> parseInteger("3.14159265358979323846")
>
> and throws for 2.7182818284590452354

Is there an issue for this?

**Comment by lucaswerkmeister** [comment]
@tombentley some of this came up in ceylon/ceylon-sdk#296.

**Comment by lucaswerkmeister** [comment]
>     parseInteger("3.14159265358979323846")

parse**Integer**? :)

I think it makes most sense to remove `FloatLiteral.float` and `IntegerLiteral.integer` completely, leaving it to the user to calculate them if needed (just like `StringLiteral` and `CharacterLiteral` already leave it to the user to handle Unicode escapes).

(Should we keep the verification code? I think yes.)

**Comment by jvasileff** [comment]
> parseInteger? :)

Ha, fixed!

> keep the verification code

Makes sense to me, I think it was just the `parseX()` functions that were too strict.

**Comment by lucaswerkmeister** [comment]
I just found a much more satisfying argument than `parseFloat` reliability to remove `IntegerLiteral.integer`: in its current form, any `ceylon.ast` based compiler must reject a program like
```ceylon
Integer overflow = 1_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000;
```
with the equivalent of a *syntax error*, because I don’t let you construct an AST for it. And this program clearly has valid syntax.

I’m not sure if an equivalent program for invalid float literals exists (`1.0e10000` is “error: literal so large it is indistinguishable from infinity”, while `parseFloat(1.0e10000)` is `Infinity`, so you could generate the correct error there), but I can justify that as consistency with `IntegerLiteral`.

**Comment by lucaswerkmeister** [comment]
Done, gone.
